// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: conversation.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createSession = `-- name: CreateSession :one
INSERT INTO sessions DEFAULT VALUES
RETURNING id, started_at
`

func (q *Queries) CreateSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, createSession)
	var i Session
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const createTurn = `-- name: CreateTurn :one
INSERT INTO turns (session_id, role, language, text, latency_ms)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, session_id, role, language, text, latency_ms, created_at
`

type CreateTurnParams struct {
	SessionID pgtype.UUID `json:"session_id"`
	Role      string      `json:"role"`
	Language  string      `json:"language"`
	Text      string      `json:"text"`
	LatencyMs *int32      `json:"latency_ms"`
}

func (q *Queries) CreateTurn(ctx context.Context, arg CreateTurnParams) (Turn, error) {
	row := q.db.QueryRow(ctx, createTurn,
		arg.SessionID,
		arg.Role,
		arg.Language,
		arg.Text,
		arg.LatencyMs,
	)
	var i Turn
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Role,
		&i.Language,
		&i.Text,
		&i.LatencyMs,
		&i.CreatedAt,
	)
	return i, err
}

const getMostRecentSession = `-- name: GetMostRecentSession :one
SELECT id, started_at FROM sessions
ORDER BY started_at DESC
LIMIT 1
`

func (q *Queries) GetMostRecentSession(ctx context.Context) (Session, error) {
	row := q.db.QueryRow(ctx, getMostRecentSession)
	var i Session
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const listTurnsBySession = `-- name: ListTurnsBySession :many
SELECT id, session_id, role, language, text, latency_ms, created_at FROM turns
WHERE session_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTurnsBySession(ctx context.Context, sessionID pgtype.UUID) ([]Turn, error) {
	rows, err := q.db.Query(ctx, listTurnsBySession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Turn
	for rows.Next() {
		var i Turn
		if err := rows.Scan(
			&i.ID,
			&i.SessionID,
			&i.Role,
			&i.Language,
			&i.Text,
			&i.LatencyMs,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
